# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/person.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protobuf/person.proto", :syntax => :proto3) do
    add_message "Person" do
      optional :name, :string, 1
      optional :id, :int32, 2
      optional :has_ponycopter, :bool, 3
    end
  end
end

Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("Person").msgclass
